repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v0.1.0
  hooks:
  - id: dbt-clean
  - id: dbt-compile
  - id: check-script-semicolon
  - id: check-script-has-no-table-name
  - id: check-model-has-all-columns
