repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v0.1.0
  hooks:
  - id: check-script-semicolon
  - id: check-script-has-no-table-name
  - id: dbt-test
  - id: dbt-docs-generate
  - id: check-model-has-all-columns
    # name: Check columns - core
    # files: ^models
  # - id: check-model-has-all-columns
  #   name: Check columns - mart
  #   files: ^models
  # - id: check-model-columns-have-desc
  #   files: ^models
